services:
  minecraft-server:
    build: .
    container_name: minecraft-server
    network_mode: "host"  # Usa a rede do host para acessar todas as portas diretamente
    volumes:
      - "./server:/mcserver"
    stdin_open: true
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: 8G  # Limita o uso máximo de memória a 12 GB
    # GPU support (for Docker runtime nvidia)
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Permite que o container use todas as GPUs disponíveis
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility  # Permissões necessárias para o uso de GPU